repos:

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
    - id: clang-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: check-added-large-files
